apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kiveexbyq-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kiveexbyq-java-quarkus-gitops